export default {
  afc: { name: 'Anchorage', st: 'AK' },
  afg: { name: 'Fairbanks', st: 'AK' },
  ajk: { name: 'Juneau', st: 'AK' },
  bou: { name: 'Denver/Boulder', st: 'CO' },
  gjt: { name: 'Grand Junction', st: 'CO' },
  pub: { name: 'Pueblo', st: 'CO' },
  lot: { name: 'Chicago', st: 'IL' },
  ilx: { name: 'Lincoln', st: 'IL' },
  ind: { name: 'Indianapolis', st: 'IN' },
  iwx: { name: 'Northern Indiana', st: 'IN' },
  dvn: { name: 'Davenport/Quad Cities', st: 'IA' },
  dmx: { name: 'Des Moines', st: 'IA' },
  ddc: { name: 'Dodge City', st: 'KS' },
  gld: { name: 'Goodland', st: 'KS' },
  top: { name: 'Topeka', st: 'KS' },
  ict: { name: 'Wichita', st: 'KS' },
  jkl: { name: 'Jackson', st: 'KY' },
  lmk: { name: 'Louisville', st: 'KY' },
  pah: { name: 'Paducah', st: 'KY' },
  dtx: { name: 'Detroit/Pontiac', st: 'MI' },
  apx: { name: 'Gaylord', st: 'MI' },
  grr: { name: 'Grand Rapids', st: 'MI' },
  mqt: { name: 'Marquette', st: 'MI' },
  dlt: { name: 'Duluth', st: 'MN' },
  mpx: { name: 'Minneapolis/Twin Cities', st: 'MN' },
  eax: { name: 'Kansas City/Pleasant Hill', st: 'MO' },
  sgf: { name: 'Springfield', st: 'MO' },
  lsx: { name: 'St. Louis', st: 'MO' },
  gid: { name: 'Hastings', st: 'NE' },
  lbf: { name: 'North Platte', st: 'NE' },
  oax: { name: 'Omaha/Valley', st: 'NE' },
  bis: { name: 'Bismarck', st: 'ND' },
  fgf: { name: 'Grand Forks', st: 'ND' },
  abr: { name: 'Aberdeen', st: 'SD' },
  unr: { name: 'Rapid City', st: 'SD' },
  fsd: { name: 'Sioux Falls', st: 'SD' },
  grb: { name: 'Green Bay', st: 'WI' },
  arx: { name: 'La Crosse', st: 'WI' },
  mkx: { name: 'Milwaukee/Sullivan', st: 'WI' },
  cys: { name: 'Cheyenne', st: 'WY' },
  riw: { name: 'Riverton', st: 'WY' },
  car: { name: 'Caribou', st: 'ME' },
  gyx: { name: 'Gray/Portland', st: 'ME' },
  box: { name: 'Boston', st: 'MA' },
  phi: { name: 'Mount Holly/Philadelphia', st: 'NJ' },
  aly: { name: 'Albany', st: 'NY' },
  bgm: { name: 'Binghamton', st: 'NY' },
  buf: { name: 'Buffalo', st: 'NY' },
  okx: { name: 'New York/Upton', st: 'NY' },
  mhx: { name: 'Newport/Morehead City', st: 'NC' },
  rah: { name: 'Raleigh', st: 'NC' },
  ilm: { name: 'Wilmington', st: 'NC' },
  cle: { name: 'Cleveland', st: 'OH' },
  iln: { name: 'Wilmington', st: 'OH' },
  pbz: { name: 'Pittsburgh', st: 'PA' },
  ctp: { name: 'State College', st: 'PA' },
  chs: { name: 'Charleston', st: 'SC' },
  cae: { name: 'Columbia', st: 'SC' },
  gsp: { name: 'Greenville-Spartanburg', st: 'SC' },
  btv: { name: 'Burlington', st: 'VT' },
  lwx: { name: 'Baltimore/Washington', st: 'VA' },
  rnk: { name: 'Blacksburg', st: 'VA' },
  akq: { name: 'Wakefield', st: 'VA' },
  rlx: { name: 'Charleston', st: 'WV' },
  gum: { name: 'Tiyan', st: 'GU' },
  hfo: { name: 'Honolulu', st: 'HI' },
  bmx: { name: 'Birmingham', st: 'AL' },
  hun: { name: 'Huntsville', st: 'AL' },
  mob: { name: 'Mobile/Pensacola', st: 'AL' },
  lzk: { name: 'North Little Rock', st: 'AR' },
  jax: { name: 'Jacksonville', st: 'FL' },
  key: { name: 'Key West', st: 'FL' },
  mlb: { name: 'Melbourne', st: 'FL' },
  mfl: { name: 'Miami', st: 'FL' },
  tae: { name: 'Tallahassee', st: 'FL' },
  tbw: { name: 'Tampa', st: 'FL' },
  ffc: { name: 'Peachtree City/Atlanta', st: 'GA' },
  lch: { name: 'Lake Charles', st: 'LA' },
  lix: { name: 'New Orleans/Baton Rouge', st: 'LA' },
  shv: { name: 'Shreveport', st: 'LA' },
  jan: { name: 'Jackson', st: 'MS' },
  abq: { name: 'Albuquerque', st: 'NM' },
  oun: { name: 'Norman/Oklahoma City', st: 'OK' },
  tsa: { name: 'Tulsa', st: 'OK' },
  sju: { name: 'San Juan', st: 'PR' },
  meg: { name: 'Memphis', st: 'TN' },
  mrx: { name: 'Morristown/Knoxville', st: 'TN' },
  ohx: { name: 'Nashville', st: 'TN' },
  ama: { name: 'Amarillo', st: 'TX' },
  ewx: { name: 'Austin/San Antonio', st: 'TX' },
  bro: { name: 'Brownsville', st: 'TX' },
  crp: { name: 'Corpus Christi', st: 'TX' },
  epz: { name: 'El Paso', st: 'TX' },
  fwd: { name: 'Fort Worth/Dallas', st: 'TX' },
  hgx: { name: 'Houston/Galveston', st: 'TX' },
  lub: { name: 'Lubbock', st: 'TX' },
  maf: { name: 'Midland/Odessa', st: 'TX' },
  sjt: { name: 'San Angelo', st: 'TX' },
  fgz: { name: 'Flagstaff', st: 'AZ' },
  psr: { name: 'Phoenix', st: 'AZ' },
  twc: { name: 'Tucson', st: 'AZ' },
  eka: { name: 'Eureka', st: 'CA' },
  lox: { name: 'Los Angeles/Oxnard', st: 'CA' },
  sto: { name: 'Sacramento', st: 'CA' },
  sgx: { name: 'San Diego', st: 'CA' },
  mtr: { name: 'San Francisco Bay Area/Monterey', st: 'CA' },
  hnx: { name: 'San Joaquin Valley/Hanford', st: 'CA' },
  boi: { name: 'Boise', st: 'ID' },
  pih: { name: 'Pocatello', st: 'ID' },
  byz: { name: 'Billings', st: 'MT' },
  ggw: { name: 'Glasgow', st: 'MT' },
  tfx: { name: 'Great Falls', st: 'MT' },
  mso: { name: 'Missoula', st: 'MT' },
  lkn: { name: 'Elko', st: 'NV' },
  vef: { name: 'Las Vegas', st: 'NV' },
  rev: { name: 'Reno', st: 'NV' },
  mfr: { name: 'Medford', st: 'OR' },
  pdt: { name: 'Pendleton', st: 'OR' },
  pqr: { name: 'Portland', st: 'OR' },
  slc: { name: 'Salt Lake City', st: 'UT' },
  sew: { name: 'Seattle', st: 'WA' },
  otx: { name: 'Spokane', st: 'WA' }
};
