// APP
const TOGGLE_SIDEBAR_OPEN: string = 'sware/app/TOGGLE_SIDEBAR_OPEN';
const UPDATE_GEOLOCATION: string = 'sware/app/UPDATE_GEOLOCATION';
const TRIGGER_IYA_PROCESSING: string = 'sware/app/TRIGGER_IYA_PROCESSING';
const QUEUE_AUDIO_ALERT: string = 'sware/app/QUEUE_AUDIO_ALERT';
const POP_AUDIO_QUEUE: string = 'sware/app/POP_AUDIO_QUEUE';
const UPDATE_USER_CONFIG: string = 'sware/app/UPDATE_USER_CONFIG';

// EVENTS MODULE
const POLLING_TIMER_UPDATE: string = 'sware/events/POLLING_TIMER_UPDATE';
const UPDATE_EVENTS_TIMEAGO: string = 'sware/events/UPDATE_EVENTS_TIMEAGO';
const TRIGGER_FILTER_EVENTS: string = 'sware/events/TRIGGER_FILTER_EVENTS';
const UPDATE_EVENTS_USER_CONFIG: string = 'sware/events/UPDATE_EVENTS_USER_CONFIG';

// GOES16 MODUE
const UPDATE_GOES16_USER_CONFIG: string = 'sware/goes16/UPDATE_GOES16_USER_CONFIG';

// FETCH MIDDLEWARE
const FETCH_REQUEST: string = 'sware/fetch/REQUEST';
const FETCH_SUCCESS: string = 'sware/fetch/SUCCESS';
const FETCH_FAILURE: string = 'sware/fetch/FAILURE';

export default {
  TOGGLE_SIDEBAR_OPEN, UPDATE_GEOLOCATION, TRIGGER_IYA_PROCESSING,
  QUEUE_AUDIO_ALERT, POP_AUDIO_QUEUE, UPDATE_USER_CONFIG,
  POLLING_TIMER_UPDATE, UPDATE_EVENTS_TIMEAGO,
  UPDATE_EVENTS_USER_CONFIG, TRIGGER_FILTER_EVENTS,
  FETCH_REQUEST, FETCH_SUCCESS, FETCH_FAILURE, UPDATE_GOES16_USER_CONFIG,
};
